HealthCareSys/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('accounts.urls')),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^',include('healthcare.urls')),
    
]

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^updateuser/$', views.UserFormUpdate.as_view(), name='userupdate'),
    #url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^user/(?P<pk>[0-9]+)/', views.UserDetail.as_view(), name='user-detail'),
    url(r'^doctor/(?P<pk>[0-9]+)/', views.DoctorDetail.as_view(), name='doctor-detail'),
    url(r'^home/$', views.UserFormView.as_view(), name='home'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

healthcare/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'healthcare'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^appointment/$', views.AppointmentCreate.as_view(), name='book-appointment'),
    url(r'^appointment/(?P<pk>[0-9]+)/', views.AppointmentDetail.as_view(), name='appointment-detail'),
    url(r'^edit-appointment/(?P<pk>[0-9]+)/$', views.AppointmentUpdate.as_view(), name='appointment-update'),
    url(r'^transactions/$', views.TransactionListView.as_view(), name='transactions'),
    url(r'^transaction/(?P<pk>[0-9]+)/', views.TransactionDetail.as_view(), name='transaction-detail'),
    url(r'^search/', views.search, name='search'),
    url(r'^print/', views.print_report, name='print'),
]

healthcare/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime 
from accounts.models import DoctorProfile
from django.core.urlresolvers import reverse
from django.db import transaction

class Location(models.Model):
    location_id = models.AutoField(primary_key=True)
    location_name = models.CharField(max_length=500)

    def __str__(self):
        return self.location_name

class Hospital(models.Model):
    name = models.CharField(max_length=100)
    location = models.ForeignKey(Location)
    contact = models.CharField(max_length=100, default='123456789')
    email = models.CharField(max_length=100,default='hospital_email@gmail.com')
    amount = models.PositiveIntegerField(default=100)

    def __str__(self):
        return self.name

class Department(models.Model):
    department_id = models.AutoField(primary_key=True)
    department_name = models.CharField(max_length=500)

    def __str__(self):
        return self.department_name

class Transaction(models.Model):
    from_user = models.ForeignKey(User, related_name='from_user')
    to_user = models.ForeignKey(User, related_name='to_user')
    time = models.DateTimeField(default=datetime.now)
    amount = models.PositiveIntegerField()
    reason = models.CharField(max_length=100)
    success = models.BooleanField(default=False)

    @transaction.atomic
    def make_transaction(self,from_user, to_user, amount, reason):
        status = False
        if from_user.amount >= amount:
            from_user.amount -= amount
            to_user.amount += amount
            from_user.save()
            to_user.save()
            status = True
        transaction = Transaction(from_user=from_user.user, to_user=to_user.user, amount=amount, success=status, reason=reason)
        transaction.save()
        return transaction, status

    def get_absolute_url(self):
        return reverse('healthcare:transaction-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.id) + ': ' + str(self.from_user) + ' to ' + str(self.to_user) + ' - ' + str(self.amount)



class Appointment(models.Model):
    STATUS = (
        ('Unconfirmed', 'Unconfirmed'),
        ('Confirmed', 'Confirmed'),
    )
    appointment_id = models.AutoField(primary_key=True)
    transaction_id = models.ForeignKey(Transaction)
    user = models.ForeignKey(User)
    doctor = models.ForeignKey(DoctorProfile)
    booking_time = models.DateTimeField(default=datetime.now)
    appointment_date = models.DateField()
    appointment_time = models.TimeField(blank=True, null=True)
    prescription = models.TextField(default='Prescription will be filled by the doctor.')
    status = models.CharField(max_length=20, default='Unconfirmed', choices=STATUS)
    fee = models.PositiveIntegerField(default=500)

    def get_absolute_url(self):
        return reverse('healthcare:appointment-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.appointment_id) + ': ' + self.user.username + ' - ' + self.doctor.user.username


        

healthcare/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Appointment
from django.forms.widgets import DateInput

class AppointmentForm(forms.ModelForm):

    class Meta:
        model = Appointment
        fields = ['doctor', 'appointment_date']
        widgets = {
            'appointment_date': forms.DateInput(attrs={
            'type':'date'})
        }
            

healthcare/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .models import Hospital, Appointment, Location, Department, Transaction
from accounts.models import DoctorProfile
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.forms.widgets import DateInput
from .forms import AppointmentForm
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Q
from datetime import datetime
from django.core.mail import EmailMessage
from django.http import HttpResponse
from .resources import AppointmentResource, TransactionResource

def index(request):
    return render(request, 'healthcare/home.html')

def search(request):
    locations = Location.objects.all().order_by('location_name')
    departments = Department.objects.all().order_by('department_name')
    if not request.GET.get('location', 'none') == 'none' and not request.GET.get('specialty', 'none') == 'none':
        location = request.GET['location']
        specialty = request.GET['specialty']
        location = Location.objects.filter(location_name=location)
        hospitals = Hospital.objects.filter(location=location)
        doctors = []
        for hospital in hospitals:
            specialty = Department.objects.filter(department_name=specialty)
            doctors += DoctorProfile.objects.filter(hospital=hospital, specialization=specialty)

        return render(request, 'healthcare/search.html', {'doctors': doctors, 'locations': locations, 'departments': departments})

    return render(request, 'healthcare/search.html', {'locations': locations, 'departments': departments})

def print_report(request):
    if request.user.is_superuser:
        if request.GET.get('data', 'none') == 'appointments':
            appointment_resource = AppointmentResource()
            dataset = appointment_resource.export()
            response = HttpResponse(dataset.csv, content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="appointments.csv"'
            return response
        elif request.GET.get('data', 'none') == 'transactions':
            transaction_resource = TransactionResource()
            dataset = transaction_resource.export()
            response = HttpResponse(dataset.csv, content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="transactions.csv"'
            return response
    return redirect('/')
            

def export(request):
    person_resource = PersonResource()
    dataset = person_resource.export()
    response = HttpResponse(dataset.csv, content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="persons.csv"'
    return response

@method_decorator(login_required, name='dispatch')
class AppointmentCreate(CreateView):
    form_class = AppointmentForm
    template_name = 'healthcare/appointment_form.html'
    doctor = None

    def send_email(self, transaction):
        try:
            subject = "Invoice for Transaction %d" % transaction.id
            body = """
Greetings %s %s!
You've recently carried out a transaction on HealthCareSys. Here are the details for future reference:-

Transaction ID: %d
From: %s
To: %s
Amount: %d
DateTime: %s
Success: %s

Wishing you the best of health,
Team HealthCareSys.
""" % (transaction.from_user.first_name, transaction.from_user.last_name, transaction.id, transaction.from_user.username, transaction.to_user.username, transaction.amount, transaction.time, transaction.success)
            email = EmailMessage(subject, body, to=[transaction.from_user.email])
            email.send()
        except:
            print("Unable to send email (%s)" % transaction.from_user.email)
    def get_initial(self):
        if self.request.GET.get('doctor_id') and DoctorProfile.objects.filter(id=self.request.GET['doctor_id']):
            return { 'doctor': DoctorProfile.objects.get(id=self.request.GET['doctor_id'])}
    
    def form_valid(self, form):
        appointment = form.save(commit=False)
        appointment.user = self.request.user
        appointment.fee = appointment.doctor.consultation_fee
        
        transaction = Transaction()
        transaction, success = transaction.make_transaction(from_user=self.request.user.userprofile, to_user=appointment.doctor, amount=appointment.fee, reason="Book Appointment")
        if success:
            appointment.transaction_id = transaction
            appointment.save()
        else:
            print('Transaction %d failed' % transaction.id)
        self.send_email(transaction)
        return redirect('healthcare:index')

@method_decorator(login_required, name='dispatch')
class AppointmentUpdate(UpdateView):
    model = Appointment
    template_name = 'healthcare/appointment_update.html'        

    def dispatch(self, request, *args, **kwargs):
        if hasattr(request.user, 'doctorprofile'):
            self.fields = ['appointment_time', 'status', 'prescription']
        else:
            self.fields = ['appointment_date']
        return super(AppointmentUpdate,self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        appointment = form.save(commit=False)
        if hasattr(self.request.user, 'userprofile'):
            appointment.status = 'Unconfirmed'
            appointment.appointment_time = None
        appointment.save() 
        return redirect(self.get_success_url())

    
    
class IndexView(generic.ListView):
    template_name = 'healthcare/home.html'
    context_object_name = 'appointments'

    def get_queryset(self):
        if self.request.user.is_authenticated():
            if hasattr(self.request.user, 'userprofile'):
                return Appointment.objects.filter(user=self.request.user)
            elif hasattr(self.request.user, 'doctorprofile'):
                return Appointment.objects.filter(doctor=self.request.user.doctorprofile)
            
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)   
         
        appointments=[]
        past_appointments =[]

        upcoming_appointments = []

        if hasattr(self.request.user, 'userprofile'):
            appointments=Appointment.objects.filter(user=self.request.user)
        elif hasattr(self.request.user, 'doctorprofile'):
            appointments=Appointment.objects.filter(doctor=self.request.user.doctorprofile)
        elif (self.request.user.is_superuser):
            appointments = Appointment.objects.all()

        for appointment in appointments:
            x=datetime.combine(appointment.appointment_date,datetime.min.time())
            z=datetime.now()
            if  x < z:
                past_appointments += [appointment]
            else:
                upcoming_appointments += [appointment]
        
        context['past_appointments'] = past_appointments
        
        context['upcoming_appointments'] = upcoming_appointments
        
        return context


class AppointmentDetail(generic.DetailView):
    model = Appointment
    template_name = 'healthcare/appointment.html'

class TransactionListView(generic.ListView):
    template_name = 'healthcare/transactions.html'
    context_object_name = 'transactions'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Transaction.objects.all()
        elif self.request.user.is_authenticated():
            return Transaction.objects.filter(Q(from_user=self.request.user) | Q(to_user=self.request.user))

class TransactionDetail(generic.DetailView):
    model = Transaction
    template_name = 'healthcare/transaction-detail.html'

healthcare/templates/healthcare/admin.html
<center><h3 style="color: #dd5;">All upcoming Appointments</h3></center>
<center><div>
    {% if upcoming_appointments %}
    <table class="rwd-table">
        <thead>
            <th>ID</th>
            <th>Patient Name</th>
            <th>Doctor Name</th>
            <th>Booking Time</th>
            <th>Appointment Date</th>
            <th>Appointment Time</th>
            <th>Status</th>
        </thead>
        <tbody>
            {% for upcoming_appointment in upcoming_appointments %}
            <tr onclick=window.location="{% url 'healthcare:appointment-detail' upcoming_appointment.pk %}">
                <td>{{ upcoming_appointment.pk }}</td>
                <td>{{ upcoming_appointment.user.first_name }} {{ upcoming_appointment.user.last_name }}</td>
                <td>{{ upcoming_appointment.doctor.user.first_name }} {{ upcoming_appointment.doctor.user.last_name }}</td>
                <td>{{ upcoming_appointment.booking_time }}</td>
                <td>{{ upcoming_appointment.appointment_date }}</td>
                <td>{{ upcoming_appointment.appointment_time }}</td>
                <td>{{ upcoming_appointment.status }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h3>There are no upcoming appointments!</h3>
    {% endif %}
    
    
    <center><h3 style="color: #dd5;">All past Appointments</h3></center>
    {% if past_appointments %}
    <table class="rwd-table">
        <thead>
            <th>ID</th>
            <th>Patient Name</th>
            <th>Doctor Name</th>
            <th>Booking Time</th>
            <th>Appointment Date</th>
            <th>Appointment Time</th>
            <th>Status</th>
        </thead>
        <tbody>
            {% for past_appointment in past_appointments %}
            <tr onclick=window.location="{% url 'healthcare:appointment-detail' past_appointment.pk %}">
                <td>{{ past_appointment.pk }}</td>
                <td>{{ past_appointment.user.first_name }} {{ past_appointment.user.last_name }}</td>
                <td>{{ past_appointment.doctor.user.first_name }} {{ past_appointment.doctor.user.last_name }}</td>
                <td>{{ past_appointment.booking_time }}</td>
                <td>{{ past_appointment.appointment_date }}</td>
                <td>{{ past_appointment.appointment_time }}</td>
                <td>{{ past_appointment.status }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h3>There are no previous appointments!</h3>
    {% endif %}
</table>

<center><button class="button-three" onclick="window.location.href='{% url 'healthcare:print' %}?data=appointments'">Print Report</button></center>

</div></center>

healthcare/templates/healthcare/appointment.html
{% extends 'healthcare/base.html' %}
{% block title %}Appointment{% endblock %}
{% block body %}
        {% if request.user.is_superuser or appointment.user == request.user or appointment.doctor == request.user.doctorprofile%}
            <!-- <div class="container" style="background-color: rgba(249, 249, 249, 0.835); opacity:1"> -->
            <center><h1 style="color: #dd5;">Appointment Details</h1>
                <table class="rwd-table">
                    <tr>
                        <th>ID</th>
                        <td>{{ appointment.pk }}</td>
                    </tr>
                    <tr>
                        <th>Patient Name</th>
                        <td>{{ appointment.user.first_name }} {{ appointment.user.last_name }}</td>
                    </tr>
                    <tr onclick=window.location="{% url 'accounts:doctor-detail' appointment.doctor.pk %}">
                        <th>Doctor Name</th>
                        <td>{{ appointment.doctor.user.username }}</td>
                    </tr>
                    <tr>
                        <th>Booking Time</th>
                        <td>{{ appointment.booking_time }}</td>
                    </tr>
                    <tr>
                        <th>Appointment Date</th>
                        <td>{{ appointment.appointment_date }}</td>
                    </tr>
                    <tr>
                        <th>Appointment Time</th>
                        <td>{{ appointment.appointment_time }}</td>
                    </tr>
                    <tr>
                        <th>Status</th>
                        <td>{{ appointment.status }}</td>
                    </tr>
                    <tr>
                        <th>Prescription</th>
                        <td>{{ appointment.prescription }}</td>
                    </tr>
                    <tr>
                        <th>Fee</th>
                        <td>{{ appointment.fee }}</td>
                    </tr>
                </table>
                {% if request.user.is_superuser %}
                <center><button class="button-three" onclick="window.location.href='/admin/healthcare/appointment/{{ appointment.pk }}/change/'">Edit Appointment</button></center>
                {% else %}
                <center><button class="button-three" onclick="window.location.href='{% url 'healthcare:appointment-update' appointment.pk %}'">Edit Appointment</button></center>
                {% endif %}
        {% else %}
              </center>

            <p>You are not authorized to view this page!</p>
        {% endif %}
{% endblock %}

healthcare/templates/healthcare/appointment_form.html
{% extends 'healthcare/base.html' %}
{% block title %}Book Appointment{% endblock %}

{% block body %}
<div>
  <div class="panel-body">
    <form id="contact" class="search-container" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <style>
        #id_appointment_date{
          float:center;
          margin: 0 auto;
          width: 100%;
          height: 45px;
          padding: 0 20px;
          font-size: 2rem;
          border: 1px solid #D0CFCE;
          outline: none;
        }
        select#id_doctor{
          float:center;
          margin: 0 auto;
          width: 100%;
          height: 45px;
          padding: 0 20px;
          font-size: 2rem;
          border: 1px solid #D0CFCE;
          outline: none;
        }
        </style>
        <div style="float:center;">
          <center><h2 style="color: #F96;	display: block;	font-size: 30px;font-weight: 400;">Book Appointment<h2><br /></center>
        {% include 'registration/form-template.html'%}

        <div class="form-group">
            <center><button class="button-three">Book Appointment</button></center>
        </div>
        </div>
    </form>
</div>
</div>
{% endblock %}

healthcare/templates/healthcare/appointment_update.html
{% extends 'healthcare/base.html' %}
{% block title %}Update Appointment{% endblock %}

{% block body %}
<div>
    <div class="panel-body">
        <form id="contact" class="search-container" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <style>
                input#id_appointment_date{
                    float:center;
                    margin: 0 auto;
                    width: 100%;
                    height: 45px;
                    padding: 0 20px;
                    font-size: 2rem;
                    border: 1px solid #D0CFCE;
                }
                input#id_appointment_time{
                    float:center;
                    margin: 0 auto;
                    width: 100%;
                    height: 45px;
                    padding: 0 20px;
                    font-size: 2rem;
                    border: 1px solid #D0CFCE;
                }
                textarea#id_prescription{
                    float:center;
                    margin: 0 auto;
                    width: 100%;
                    height: 250px;
                    padding: 0 20px;
                    font-size: 2rem;
                    border: 1px solid #D0CFCE;
                    outline: none;
                }
                select#id_status{
                    float:center;
                    margin: 0 auto;
                    width: 100%;
                    height: 45px;
                    padding: 0 20px;
                    font-size: 2rem;
                    border: 1px solid #D0CFCE;
                    outline: none;
                }
                input#id_fee{
                    float:center;
                    margin: 0 auto;
                    width: 100%;
                    height: 45px;
                    padding: 0 20px;
                    font-size: 2rem;
                    border: 1px solid #D0CFCE;
                    outline: none;
                    
                }
            </style>
            <div style="float:center;">
                <center><h2 style="color: #F96;	display: block;	font-size: 30px;font-weight: 400;">Update Appointment<h2><br /></center>
                    {% if appointment.doctor.user == request.user %}
                        <center><div><h2 style="color:#F96;">{{ appointment.user }}</h2><br  /></div></center>
                    {% else %}
                        <center><div><h2 style="color:#F96;">{{ appointment.doctor.user.first_name }} {{ appointment.doctor.user.last_name }}</h2><br /></div></center>
                    {% endif %}
                    {% include 'registration/form-template.html'%}
                    <script>
                            $('#id_appointment_time').attr('type', 'time');
                            $('#id_appointment_date').attr('type', 'date');
                        
                    </script>
                    <div class="form-group">
                    <center><button class="button-three">Update</button></center>
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% endblock %}
    

healthcare/templates/healthcare/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}HealthCareSys{% endblock %}</title>
    {% load staticfiles %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/profile.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/main.css" %}" rel="stylesheet" type="text/css">
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/jquery.easing.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/script.js" %}"></script>
</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">
    <section id="banner" class="banner">
      <div class="bg-color">
    <nav class="navbar navbar-default navbar-fixed-top" >
      <div class="container">
        <div class="col-md-12">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'healthcare:index' %}"><img src="{% static "img/logo.png" %}" class="img-responsive" style="width: 140px; margin-top: -30%;"></a>
          </div>
          <div class="collapse navbar-collapse navbar-right" id="myNavbar">
            <ul class="nav navbar-nav">
              {% if request.user.is_authenticated %}
                {% if request.user.userprofile %}
                <li class=""><a>₹{{ request.user.userprofile.amount }}</a></li>
                {% else %}
                <li class=""><a>₹{{ request.user.doctorprofile.amount }}</a></li>
                {% endif %}
                {% endif %}
              {% if request.user.is_superuser %}
              <li class=""><a href="/admin/">Admin</a></li>
              {% elif not request.user.doctorprofile %}
              <li class=""><a href="{% url 'healthcare:search' %}">Search</a></li>
              {% endif %}
              {% if request.user.is_authenticated %}
              <li class=""><a href="{% url 'healthcare:index' %}">Appointments</a></li>
              <li class=""><a href="{% url 'healthcare:transactions' %}">Transactions</a></li>
              {% else %}
              <li class=""><a href="{% url 'accounts:register' %}">Register</a></li>
              {% endif %}
              {% if request.user.is_authenticated and request.user.doctorprofile %}
              <li class=""><a href="{% url 'accounts:doctor-detail' request.user.doctorprofile.pk %}">Profile</a></li>
              {% elif request.user.is_authenticated and request.user.userprofile %}
              <li class=""><a href="{% url 'accounts:user-detail' request.user.userprofile.pk %}">Profile</a></li>
              {% elif not request.user.is_authenticated %}
              <li class=""><a href="{% url 'accounts:home' %}?role=doctor">Doctor</a></li>
              {% endif %}
              <li class="">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'accounts:logout' %}">
                        Logout
                    </a>
                {% else %}
                    <a href="{% url 'accounts:login' %}">
                        Login
                    </a>
                {% endif %}
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="banner-info">
          {% block body %}
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
</section>

</body>
</html>

healthcare/templates/healthcare/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
</div>
{% endfor %}

healthcare/templates/healthcare/home.html
{% extends 'healthcare/base.html' %}
{% block title %}Home{% endblock %}

{% block body %}
    {% if request.user.is_authenticated %}
        {% if user.doctorprofile  %}

        {% include 'healthcare/doctor.html' %}
        {% elif user.userprofile %}
        {% include 'healthcare/user.html' %}
        {% elif user.is_superuser %}
        {% include 'healthcare/admin.html' %}

        {% endif %}
    {% else %}
    {% include 'healthcare/homepage.html' %}

    {% endif %}
{% endblock %}

healthcare/templates/healthcare/search.html
{% extends 'healthcare/base.html' %}
{% block title %}Home{% endblock %}
{% load staticfiles %}
{% block body %}
<p>
  <div >
    <div class="panel-body">
      <center><h2 style="color: #F96;	display: block;	font-size: 30px;font-weight: 400;">Search<h2><br /></center>
      <form class="search-container" action="" method="GET" enctype="multipart/form-data">
        <div>
          <select name="location" class="form-control" type="text" id="search-bar" required>
            <option value="" selected="selected">Location</option>
            {% for location in locations %}
              <option value="{{ location }}">{{ location }}</option>
            {% endfor %}
          </select>
          <br />
          <select name="specialty" class="form-control" type="text" id="search-bar" required>
              <option value="" selected="selected">Department</option>
            {% for department in departments %}
              <option value="{{ department }}">{{ department }}</option>
            {% endfor %}
          </select>
          <br />
          <div class="form-group">
            <center><button class="button-three">Search</button></center>
          </div>
        </div>
      </form>
    </div>
    
    {% if doctors %}
    <div class="container" style="background-color: #F9F9F9;opacity:0.86">
      <ul id="results">
        {% for doctor in doctors %}
        <li>
          <div class="list-left">
            <img id="img{{ doctor.pk }}" src="/static/img/doctor1.jpg"  width="100px" height="285px">
            <script>
                var num = ({{ doctor.pk }} % 4) + 1;
                var source = "/static/img/doctor" + num + ".jpg";
                document.getElementById("img{{ doctor.pk }}").src = source;
            </script>
          </div>
          <div class="list-right">
            <h2>Dr.{{ doctor.user.first_name }} {{ doctor.user.last_name }}</h2>
            <br><h3>{{ doctor.hospital }}</h3><br>
            <h3>{{ doctor.specialization }}</h3><br>
            <h3>₹{{ doctor.consultation_fee }}</h3><br>
            
            <div class="sub-main">
              <button class="button-three" onclick=location.href="{% url 'healthcare:book-appointment' %}?doctor_id={{ doctor.id }}">Appointment</button>
            </div>
          </li>
          {% endfor %}
        </ul>
        {% endif %}
      </div>
      
    </div>
  </div>
  
</p>
{% endblock %}

healthcare/templates/healthcare/transactions.html
{% extends 'healthcare/base.html' %}
{% block body %}
<center><h3 style="color: #dd5;">Your Transaction History</h3></center>
<center><div>
{% if transactions %}
<table class="rwd-table">
  <thead>
      <th>ID</th>
      <th>From</th>
      <th>To</th>
      <th>Transaction Time</th>
      <th>Amount</th>
      <th>Reason</th>
      <th>Status</th>
  </thead>
  <tbody>
      {% for transaction in transactions %}
      <tr onclick=window.location="{% url 'healthcare:transaction-detail' transaction.pk %}">
          <td>{{ transaction.pk }}</td>
          <td>{{ transaction.from_user }}</td>
          <td>{{ transaction.to_user }}</td>
          <td>{{ transaction.time }}</td>
          <td>{{ transaction.amount }}</td>
          <td>{{ transaction.reason }}</td>
          <td>{{ transaction.status }}</td>
      </tr>
      {% endfor %}
  </tbody>
</table>
{% else %}
<h3>You have no transactions!</h3>
{% endif %}
</table>
{% if request.user.is_superuser %}
<center><button class="button-three" onclick="window.location.href='{% url 'healthcare:print' %}?data=transactions'">Print Report</button></center>
{% endif %}
</div></center>
{% endblock %}